# === Java 21 Service B ===
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:java21
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: laptop1
      containers:
        - name: config-service
          image: config-service:java17
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: NodePort
  selector:
    app: config-service
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service
          image: discovery-service:java17
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  type: NodePort
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30002


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-status-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-status-service
  template:
    metadata:
      labels:
        app: health-status-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: laptop1 #hnaya kadir fin baghi deplwayih laptop2 ismail 3 ayman
      containers:
        - name: health-status-service
          image: health-status-service:java17
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: health-status-service
spec:
  type: NodePort
  selector:
    app: health-status-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetching-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetching-data-service
  template:
    metadata:
      labels:
        app: fetching-data-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: laptop1 #hnaya kadir fin baghi deplwayih laptop2 ismail 3 ayman
      containers:
        - name: fetching-data-service
          image: fetching-data-service:java21
          ports:
            - containerPort: 8082

#zido dakchi dyalkom

---
apiVersion: v1
kind: Service
metadata:
  name: fetching-data-service
spec:
  type: NodePort
  selector:
    app: fetching-data-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30004