
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: NodePort
  selector:
    app: config-service
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  type: NodePort
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: health-monitoring-service
spec:
  type: NodePort
  selector:
    app: health-monitoring-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30003

---
apiVersion: v1
kind: Service
metadata:
  name: fetching-data-service
spec:
  type: NodePort
  selector:
    app: fetching-data-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30004

---
apiVersion: v1
kind: Service
metadata:
  name: end-of-life-service
spec:
  type: NodePort
  selector:
    app: end-of-life-service
  ports:
    - port: 8005
      targetPort: 8005
      nodePort: 30005

---
apiVersion: v1
kind: Service
metadata:
  name: collision-service
spec:
  type: NodePort
  selector:
    app: collision-service
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30006

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30007

