pipeline{
    agent any

    when {
        anyOf {
            changeset "SpaceApp/SpringBackend/UserService/**"
        }
    }

    stages {
        stage ("building jar and tests"){
            steps{
                sh "mvn clean package -DskipTests=true"
                sh "mvn test" 
            }
            post {
                always {
                    publishTestResults testResultsPattern: 'target/surefire-reports/*.xml'
                }
            }
        }

        stage ("building image"){
            steps{
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds',usernameVariable:'DOCKERHUB_USER',passwordVariable:'DOCKERHUB_TOKEN')]){
                    //def tag = env.BUILD_NUMBER
                    //to be imrpoved to use a build number now we will stick with static latest
                    //def image = "\$DOCKERHUB_USER/health-monitoring-service:${tag}"
                    def image = "\$DOCKERHUB_USER/health-monitoring-service:latest"

                    script {
                        sh "echo \$DOCKERHUB_TOKEN | docker login -u \$DOCKERHUB_USER --password-stdin"
                        sh "docker build -t ${image} ."
                        sh "docker push ${image}"
                        sh "docker logout"
                    }
                }
            }
        }

        stage ("deploying to kubernetess"){
            steps{
                sh 'kubectl apply -f Deployment.yaml' // we should fix the pull image issue when we use the env.BUILD_NUMBER for the image tag
                sh 'kubectl apply -f service.yaml'
            }
        }
    }
}