apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1  # Reduce to 2 to lower memory pressure
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: youssefbouraoui1/frontend_spaceapp:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "6Gi"  # Reduced from 8Gi to be conservative
            cpu: "1"
          requests:
            memory: "3Gi"
            cpu: "0.5"