pipeline {
  agent any

  stages {
    stage('Build Docker Image') {
      steps {
        script {
          // Build image
          sh "docker build -t frontend_spaceapp ."
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        echo 'Deploying frontend to Kubernetes...'
        sh 'kubectl apply -f deployment.yml'
        sh 'kubectl apply -f service.yml'
      }
    }
  }

  post {
    success {
      echo 'Pipeline finished successfully!'
    }
    failure {
      echo 'Pipeline failed!'
    }
  }
}
