pipeline {
  agent any

  environment {
    DOCKERHUB_USER = 'youssefbouraoui1'
    IMAGE_NAME = 'frontend_spaceapp'
    DOCKER_TAG = 'latest'
  }

  stages {
    stage('Checkout Code') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      //when {
        //changeset "SpaceApp/frontend/**"
      //}
      steps {
        dir('SpaceApp/frontend') {
          script {
            sh "docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:${DOCKER_TAG} ."
          }
        }
      }
    }

    stage('Push to Docker Hub') {
     // when {
      //  changeset "SpaceApp/frontend/**"
      //}
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_TOKEN')]) {
          sh "echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin"
          dir('SpaceApp/frontend') {
            script {
              def image = "${DOCKERHUB_USER}/${IMAGE_NAME}:${DOCKER_TAG}"
              sh "docker push ${image}"
            }
          }
          sh "docker logout"
        }
      }
    }

    stage('Deploy to Kubernetes') {
     // when {
     //   changeset "SpaceApp/frontend/**"
     // }
      steps {
        dir('SpaceApp/frontend') {
          script {
            echo 'Deploying frontend to Kubernetes...'
            withCredentials([file(credentialsId: 'kubeconfig-secret-id', variable: 'KUBECONFIG')]) {
                  sh 'kubectl apply -f deployement.yml --validate=false'
            }
            sh 'kubectl apply -f services.yml'
          }
        }
      }
    }
  }

  post {
    success {
      echo '✅ Frontend deployed and image pushed to Docker Hub successfully.'
    }
    failure {
      echo '❌ Pipeline failed.'
    }
  }
}
