all:
  children:
    control_plane:
      hosts:
        machine1:
          ansible_host: "{{ lookup('env','CONTROL_PLANE_IP') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','YOUSSEF_KEY') }}"
    worker_nodes:
      hosts:
        machine2:
          ansible_host: "{{ lookup('env','AYMAN_VM1') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','AYMAN_KEY') }}"
        machine3:
          ansible_host: "{{ lookup('env','AYMAN_VM2') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','AYMAN_KEY') }}"
        machine4:
          ansible_host: "{{ lookup('env','MACHINE_YOUSSEF2_IP') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','YOUSSEF_KEY') }}"
        machine5:
          ansible_host: "{{ lookup('env','ISMAIL_VM1') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','ISMAIL_KEY') }}"
        machine6:
          ansible_host: "{{ lookup('env','ISMAIL_VM2') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','ISMAIL_KEY') }}"
