---
- name: Install Kubernetes tools (kubeadm, kubelet, kubectl)
  hosts: all
  become: yes
  tasks:

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download the Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
        mode: '0644'
      # Only download if not exists
      force: no

    - name: Add Kubernetes apt repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
      # Only create if not exists
      force: no

    - name: Update apt package cache after adding Kubernetes repo
      apt:
        update_cache: yes

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name:
          - kubeadm=1.34.0-00
          - kubelet=1.34.0-00
          - kubectl=1.34.0-00
        state: present
        allow_downgrade: yes

    - name: Hold kubeadm, kubelet, and kubectl to prevent automatic upgrades
      command: apt-mark hold kubelet kubeadm kubectl
      args:
        warn: false

    - name: Enable and start kubelet service
      systemd:
        name: kubelet
        enabled: yes
        state: started
