- name: Install containerd on all hosts
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install containerd package
      apt:
        name: containerd
        state: latest

    - name: Create containerd configuration directory
      file:
        path: /etc/containerd
        state: directory

    - name: Generate default containerd configuration
      shell: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: Enable and start containerd service
      systemd:
        name: containerd
        enabled: yes
        state: started
