pipeline{
    agent any

    when{
        anyOf{
            changeset "SpaceApp/SpringBackend/CollisionService/**"
        }
    }

    stages{
        stage("building jar file and executing tests once"){
            steps{
                sh "mvn clean package"
            }
            post {
                always {
                    publishTestResults testResultsPattern: 'target/surefire-reports/*.xml'
                }
            }
        }

        stage("building docker image and pushing to dockerhub"){
            steps{
                withCredentials([usernamePassword(credentialsId: 'dockerHubCreds', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_TOKEN')]){
                    def image = "${DOCKERHUB_USERNAME}/collision-service:latest"

                    sh "echo \$DOCKERHUB_TOKEN | docker login -u \$DOCKERHUB_USERNAME --password-stdin"
                    sh "docker build -t ${image} ."
                    sh "docker push ${image}"
                    sh 'docker logout'
                }
            }
        }

        stage("deploying to kubernetes"){
            steps{
                sh "kubectl apply -f deployment.yml"
                sh "kubectl apply -f service.yml"
            }
        }
    }
}