apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-service
  template:
    metadata:
      labels:
        app: django-service
    spec:
      containers:
        - name: django-service
          image: youssefbouraoui1/django-service:build-11  # 🟡 Mets à jour dynamiquement si besoin
          ports:
            - containerPort: 9003  # ✅ Correspond à ton Dockerfile
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.default.svc.cluster.local:9092
      imagePullSecrets:
        - name: regcred