apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort  # or ClusterIP depending on your networking setup
