export const mockCollisionData = [
  {
    id: "col-001",
    primaryObject: "STARLINK-1234",
    secondaryObject: "COSMOS-1408 Debris",
    primaryNoradId: "48208",
    secondaryNoradId: "49263",
    primaryType: "Satellite",
    secondaryType: "Debris",
    primarySize: "Medium",
    secondarySize: "Small",
    timeToClosestApproach: "4h 12m",
    missDistance: "125 m",
    probability: "0.0234",
    relativeVelocity: "14.2 km/s",
    riskLevel: "High",
    conjunctionTime: "2025-05-06T15:30:00Z",
    lastUpdated: "12 minutes ago",
    orbitType: "LEO",
    primaryOrbit: {
      semiMajorAxis: 6978,
      eccentricity: 0.0001,
      inclination: 53.0,
      raan: 180.0,
      argOfPerigee: 0.0,
      meanAnomaly: 0.0,
    },
    secondaryOrbit: {
      semiMajorAxis: 6980,
      eccentricity: 0.0002,
      inclination: 52.8,
      raan: 179.5,
      argOfPerigee: 1.2,
      meanAnomaly: 359.0,
    },
  },
  {
    id: "col-002",
    primaryObject: "ISS",
    secondaryObject: "FENGYUN-1C Debris",
    primaryNoradId: "25544",
    secondaryNoradId: "30912",
    primaryType: "Space Station",
    secondaryType: "Debris",
    primarySize: "Large",
    secondarySize: "Small",
    timeToClosestApproach: "12h 45m",
    missDistance: "350 m",
    probability: "0.0056",
    relativeVelocity: "11.8 km/s",
    riskLevel: "Medium",
    conjunctionTime: "2025-05-06T23:45:00Z",
    lastUpdated: "25 minutes ago",
    orbitType: "LEO",
    primaryOrbit: {
      semiMajorAxis: 6780,
      eccentricity: 0.0006,
      inclination: 51.6,
      raan: 120.0,
      argOfPerigee: 0.0,
      meanAnomaly: 0.0,
    },
    secondaryOrbit: {
      semiMajorAxis: 6785,
      eccentricity: 0.0012,
      inclination: 52.1,
      raan: 119.5,
      argOfPerigee: 1.5,
      meanAnomaly: 358.5,
    },
  },
  {
    id: "col-003",
    primaryObject: "NOAA-19",
    secondaryObject: "SL-16 R/B",
    primaryNoradId: "33591",
    secondaryNoradId: "28353",
    primaryType: "Weather Satellite",
    secondaryType: "Rocket Body",
    primarySize: "Medium",
    secondarySize: "Large",
    timeToClosestApproach: "1d 3h",
    missDistance: "725 m",
    probability: "0.0012",
    relativeVelocity: "9.7 km/s",
    riskLevel: "Low",
    conjunctionTime: "2025-05-07T14:30:00Z",
    lastUpdated: "1 hour ago",
    orbitType: "LEO",
    primaryOrbit: {
      semiMajorAxis: 7200,
      eccentricity: 0.0014,
      inclination: 98.7,
      raan: 45.0,
      argOfPerigee: 0.0,
      meanAnomaly: 0.0,
    },
    secondaryOrbit: {
      semiMajorAxis: 7210,
      eccentricity: 0.0022,
      inclination: 97.9,
      raan: 44.2,
      argOfPerigee: 2.1,
      meanAnomaly: 357.8,
    },
  },
  {
    id: "col-004",
    primaryObject: "ONEWEB-0234",
    secondaryObject: "IRIDIUM-33 Debris",
    primaryNoradId: "47438",
    secondaryNoradId: "33872",
    primaryType: "Communication Satellite",
    secondaryType: "Debris",
    primarySize: "Medium",
    secondarySize: "Small",
    timeToClosestApproach: "6h 20m",
    missDistance: "180 m",
    probability: "0.0178",
    relativeVelocity: "13.5 km/s",
    riskLevel: "Medium",
    conjunctionTime: "2025-05-06T17:20:00Z",
    lastUpdated: "30 minutes ago",
    orbitType: "LEO",
    primaryOrbit: {
      semiMajorAxis: 7000,
      eccentricity: 0.0008,
      inclination: 87.9,
      raan: 220.0,
      argOfPerigee: 0.0,
      meanAnomaly: 0.0,
    },
    secondaryOrbit: {
      semiMajorAxis: 7005,
      eccentricity: 0.0015,
      inclination: 86.4,
      raan: 219.5,
      argOfPerigee: 1.8,
      meanAnomaly: 359.2,
    },
  },
  {
    id: "col-005",
    primaryObject: "LANDSAT-8",
    secondaryObject: "COSMOS-2251 Debris",
    primaryNoradId: "39084",
    secondaryNoradId: "35119",
    primaryType: "Earth Observation",
    secondaryType: "Debris",
    primarySize: "Medium",
    secondarySize: "Small",
    timeToClosestApproach: "2d 8h",
    missDistance: "850 m",
    probability: "0.0008",
    relativeVelocity: "10.2 km/s",
    riskLevel: "Low",
    conjunctionTime: "2025-05-08T19:00:00Z",
    lastUpdated: "2 hours ago",
    orbitType: "LEO",
    primaryOrbit: {
      semiMajorAxis: 7080,
      eccentricity: 0.0001,
      inclination: 98.2,
      raan: 150.0,
      argOfPerigee: 0.0,
      meanAnomaly: 0.0,
    },
    secondaryOrbit: {
      semiMajorAxis: 7085,
      eccentricity: 0.0018,
      inclination: 97.5,
      raan: 149.2,
      argOfPerigee: 2.5,
      meanAnomaly: 358.0,
    },
  },
  {
    id: "col-006",
    primaryObject: "STARLINK-2468",
    secondaryObject: "STARLINK-3579",
    primaryNoradId: "48932",
    secondaryNoradId: "49876",
    primaryType: "Communication Satellite",
    secondaryType: "Communication Satellite",
    primarySize: "Medium",
    secondarySize: "Medium",
    timeToClosestApproach: "3h 55m",
    missDistance: "95 m",
    probability: "0.0267",
    relativeVelocity: "8.3 km/s",
    riskLevel: "High",
    conjunctionTime: "2025-05-06T14:55:00Z",
    lastUpdated: "15 minutes ago",
    orbitType: "LEO",
    primaryOrbit: {
      semiMajorAxis: 6950,
      eccentricity: 0.0001,
      inclination: 53.0,
      raan: 90.0,
      argOfPerigee: 0.0,
      meanAnomaly: 0.0,
    },
    secondaryOrbit: {
      semiMajorAxis: 6950,
      eccentricity: 0.0001,
      inclination: 53.0,
      raan: 90.1,
      argOfPerigee: 0.2,
      meanAnomaly: 359.8,
    },
  },
  {
    id: "col-007",
    primaryObject: "SENTINEL-2A",
    secondaryObject: "UNKNOWN DEBRIS",
    primaryNoradId: "40697",
    secondaryNoradId: "Unknown",
    primaryType: "Earth Observation",
    secondaryType: "Debris",
    primarySize: "Medium",
    secondarySize: "Small",
    timeToClosestApproach: "8h 10m",
    missDistance: "210 m",
    probability: "0.0089",
    relativeVelocity: "12.1 km/s",
    riskLevel: "Medium",
    conjunctionTime: "2025-05-06T19:10:00Z",
    lastUpdated: "40 minutes ago",
    orbitType: "LEO",
    primaryOrbit: {
      semiMajorAxis: 7170,
      eccentricity: 0.0001,
      inclination: 98.5,
      raan: 130.0,
      argOfPerigee: 0.0,
      meanAnomaly: 0.0,
    },
    secondaryOrbit: {
      semiMajorAxis: 7175,
      eccentricity: 0.0025,
      inclination: 97.8,
      raan: 129.5,
      argOfPerigee: 1.9,
      meanAnomaly: 358.5,
    },
  },
  {
    id: "col-008",
    primaryObject: "WORLDVIEW-4",
    secondaryObject: "BREEZE-M R/B",
    primaryNoradId: "41848",
    secondaryNoradId: "37756",
    primaryType: "Earth Observation",
    secondaryType: "Rocket Body",
    primarySize: "Medium",
    secondarySize: "Large",
    timeToClosestApproach: "1d 15h",
    missDistance: "520 m",
    probability: "0.0023",
    relativeVelocity: "11.3 km/s",
    riskLevel: "Low",
    conjunctionTime: "2025-05-08T02:00:00Z",
    lastUpdated: "3 hours ago",
    orbitType: "LEO",
    primaryOrbit: {
      semiMajorAxis: 7060,
      eccentricity: 0.0001,
      inclination: 97.9,
      raan: 200.0,
      argOfPerigee: 0.0,
      meanAnomaly: 0.0,
    },
    secondaryOrbit: {
      semiMajorAxis: 7070,
      eccentricity: 0.0035,
      inclination: 96.8,
      raan: 199.0,
      argOfPerigee: 3.2,
      meanAnomaly: 357.0,
    },
  },
]
