spring:
  cloud:
    gateway:
      routes:
        - id : health-status-service
          uri: http://localhost:8081
          predicates :
            - Path=/api//**

        - id : fetching-data-service
          uri: http://localhost:8082
          predicates :
            - Path=/api/

        - id: collision-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/

        - id: end-of-life-service
          uri: http://localhost:8084 #http://collision-service.default.svc.cluster.local:8082
          predicates:
            - Path=/api/

        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/