spring:
  application:
    name: GatewayService
  mvc:
    cors:
      allowed-origins:
        - http://localhost:3000
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: health-monitoring-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/health/**

        - id: fetching-data-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/satellites/**,/api/v1/users/**

        - id: collision-service
          uri: http://localhost:8003
          predicates:
            - Path=/api/collisions/**

        - id: end-of-life-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/eol/**, /api/end-of-life/**

        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path= /api/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Credentials, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Methods, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Allow-Headers, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Expose-Headers, RETAIN_FIRST
            - DedupeResponseHeader=Access-Control-Max-Age, RETAIN_FIRST
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"

