spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: health-status-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/health/**, /api/status/**

        - id: fetching-data-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/data/**, /api/fetch/**

        - id: collision-service
          uri: http://localhost:8003
          predicates:
            - Path=/api/collisions/**

        - id: end-of-life-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/eol/**, /api/end-of-life/**

        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/users/**, /api/auth/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"